global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'chatwoot-langchain'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['chatwoot-langchain:5000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'chatwoot-langchain'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
    metric_relabel_configs:
      - source_labels: [container_label_com_docker_compose_service]
        target_label: service
        regex: (.+)
        replacement: $1

  # Add this job if you're using OpenTelemetry for distributed tracing
  - job_name: 'opentelemetry'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
